import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'swiper/css';
import "./globals.css";
import Announcement from "@/components/sharedUi/Announcement";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${inter.variable} antialiased bg-white overflow-hidden`}
      >
        <Announcement />
        {children}
      </body>
    </html>
  );
}
